### ISSUE TITLE
Installation du paquet sambaedu-web-common

### ISSUE THREAD

**Issue by mollef** [SambaEdu/se4#11]
Petit résumé des pb rencontrés sur SE4FS avec les paquets préversion alpha

Actuellement le paquet ne peut s'installer car certaines deps sortent en exit 1 du script postinst . Cas possibles :  
* sambaedu-boot-server lors de l'appel à config.inc 
Remarque : A ce stade le service dhcp ne démarre pas ...Faut-il récupérer le fichier de conf du se3 ?
https://github.com/SambaEdu/se4/issues/8
```
isc-dhcp-server.service - LSB: DHCP server
   Loaded: loaded (/etc/init.d/isc-dhcp-server; generated; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2018-05-19 11:27:37 CEST; 5ms ago
     Docs: man:systemd-sysv-generator(8)
  Process: 14155 ExecStart=/etc/init.d/isc-dhcp-server start (code=exited, status=1/FAILURE)
```
* sambaedu-ad-dc ou  sambaedu-ad-client ne parvient pas à tester correctement l'AD pb de lecture des params dans sambaedu.conf / pas de question debonf

**Comment by mollef** [comment]
> En revanche il faut que la conf réseau soit parfaitement faite, avec /etc/ hostname, resolv.conf, hosts, networks sans trucs incohérents, sinon cela plante lamentablement assez vite... 

Il s'agit des params suite à l'installation avec DI donc générés à l'étape précédente. Le plus simple serait p-e que je te donne l'accès à la machine en ssh... On voit ça par mail.

**Comment by jlcf** [comment]
Sur le se4fs :

J’ai vérifié le réseau le se4fs voit le se4ad en ip et en nom dns
le resolv.conf du se4fs  indique le se4ad en dns

Il y avait un petit pb dans le /etc/hosts, que j'ai corrigé, mais meme pb en suite ici:

Le serveur AD n'est pas joignable                                                                       │
     │                                                                                                         │
     │ Le serveur AD ne peut pas être joint avec les identifiants fournis.                                     │
     │                                                                                                         │
     │ Soit il n'est pas encore en service, dans ce cas vous devez commencer par le configurer en lancant....  │
     │                                                                                                         │
     │ Soit les identifiants sont incorrects.

Avec ou sans sambaedu.conf
Sans sambaedu.conf, ca donne ca a la fin :
# cat /etc/sambaedu/sambaedu.conf
ldap_base_dn = "dc=«

**Comment by denis-b** [comment]
Quand il te dit que le ad ne peut Pas être joint, si tu choisis test dans
le menu il ne te demande pas les paramètres de connexion ?

Le mar. 22 mai 2018 à 13:36, Jean-Luc CHRETIEN <notifications@github.com> a
écrit :

**Comment by jlcf** [comment]
non… il me redonne le message injoignable…

JL

**Comment by mollef** [comment]
La suite résumée là : https://github.com/SambaEdu/se4/issues/8
