### ISSUE TITLE
Paquet sambaedu  3.9.4~XP.10 

### ISSUE THREAD

**Issue by mollef** [SambaEdu/se4#13]
Bonjour à tous,

Retour sur une installation SE4AD - SE4FS à blanc
* Coté installation, c'est ok - RAS

Mon fichier de conf :

```
# cat /etc/sambaedu/sambaedu.conf
## Adresse IP du futur SE4-AD ##
se4ad_ip = "10.127.164.220"
## Nom du SE4-AD ##
se4ad_name = "se4ad"
## Adresse IP du futur SE4-FS ##
se4fs_ip = "10.127.164.210"
## Nom du futur SE4-FS ##
se4fs_name="se4fs"
## Nom de domaine samba ##
samba_domain = "clg-stage"
## Nom de domaine complet ##
domain = "clg-stage.ac-rouen.fr"
##Adresse du serveur DNS##
nameserver="10.127.164.1"
## params annuaire AD##
admin_name="Administrator"
ldap_admin_name = "Administrator"
people_rdn="OU=Users"
admin_rdn = "CN=Users"
groups_rdn="ou=Groups"
rights_rdn="ou=Rights"
parcs_rdn="ou=Parcs"
computers_rdn="CN=computers"
printers_rdn="ou=Printers"
trash_rdn="ou=Trash"
ldap_url = "ldaps://clg-stage.ac-rouen.fr"
## ad_base_dn ##
ldap_base_dn = "DC=clg-stage,DC=ac-rouen,DC=fr"
## ldap_admin_passwd ##
ldap_admin_passwd = "Sambaedu4"
sql_passwd = "FSrjSYxoJA"
```
* Première remarque, le fichier contient alternativement Maj et Min au niveau des OU. Ne devrais-je pas mettre tout en Maj ?
* Ensuite les espaces après la déclaration de la variable qui sont présents ou pas selon les lignes

Ce qui fonctionne : 

- apt-get install sambaedu installe bien les paquets sambaedu-*, sans question et sans erreur

Deux pbs rencontrés :
*  La commande suivante renvoie une erreur : 
`su www-admin -c "samba-tool user list -k yes -H ldap://se4ad.clg-stage.ac-rouen.fr"
Failed to bind - LDAP client internal error: NT_STATUS_INVALID_PARAMETER
Failed to connect to 'ldap://clg-stage.ac-rouen.fr' with backend 'ldap': LDAP client internal error: NT_STATUS_INVALID_PARAMETER ERROR(ldb): uncaught exception - LDAP client internal error: NT_STATUS_INVALID_PARAMETER`
   * Ce premier pb se règle avec la commande ` su www-admin -c "kinit -k -t /etc/sambaedu/www-sambaedu.keytab www-sambaedu@CLG-STAGE.AC-ROUEN.FR"`
   * Ensuite ça marche :+1:  
`su www-admin -c "samba-tool user list -k yes -H ldap://se4ad.clg-stage.ac-rouen.fr"
adminse3
backuppc
unattend
camembey
cariteyd
caumeile
coliber2
-----------8<-------------`
* Par contre l'interface web ne me permet pas de me connecter avec le compte _Administrator_ alors que ça marchait sur l'installation précédente çà. Effet de bord des déplacement des utilisateurs dans OU=Users ? Le compte administrateur ainsi que les utilisateurs _www-sambaedu_ et _krbtgt_ sont restés dans la branche cn=Users car ce sont des comptes système.

Comment passer en mode debug l'interface ? Je n'ai rien de spécial dans les logs apache

**Comment by jlcf** [comment]
Re,


Sur le SE4FS 3.9.4~XP.10

Le samba-tool fonctionne mais j’ai un pb avec les requettes ldap :

ldapsearch  -H ldap://10.211.55.10 -Y gssapi -b DC=sambaedu,DC=maison '(cn=*)’

OK

Mais 
avec -H ldap://sambaedu.maison <ldap://sambaedu.maison>
ou -H ldap://se4ad.sambaedu.maison <ldap://se4ad.sambaedu.maison>

Echec :
SASL/GSSAPI authentication started
ldap_sasl_interactive_bind_s: Local error (-2)
	additional info: SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server not found in Kerberos database)
m


Alors que la résolution est ok…



C’est pas lié avec le pb d’auth sur l’interface web ?

Je vois pas de solution pour l’instant…

JL

**Comment by mollef** [comment]
Le 06/06/2018 à 21:53, Jean-Luc Chrétien a écrit :
> Re,
>
> J’ai trouvé :
>
> Il faut disabled ipv6 dans  /etc/sysctl.conf
> # désactivation de l’auto configuration pour toutes les interfaces
> net.ipv6.conf.all.autoconf = 0
>
> # désactivation de ipv6 pour les nouvelles interfaces (ex:si ajout de carte 
> réseau)
> net.ipv6.conf.default.disable_ipv6 = 1
>
> # désactivation de l’auto configuration pour les nouvelles interfaces
> net.ipv6.conf.default.autoconf = 0
>
>
> sysctl -p
>
>
Super, bravo ! :)


> Apres le ldapsearch est okay…
> Le pb auth interface subsiste, il faut regarder dans les filtres des request 
> ldap… On va voir ca demain…
>
> JL
>
>> Le 6 juin 2018 à 20:45, Jean-Luc Chrétien <jean-luc.chretien@ac-caen.fr

**Comment by denis-b** [comment]
J'ai fait des tests : 
- le se4ad n'est pas configuré pour être serveur ntp. C'est ce qui fout la zone pour se4fs, et provoque l'erreur aléatoire de kerberos. 
- il manque aussi la conf de /etc/systemd/timesyncd.conf sur se4fs
- la desactivation d'ipv6 ne change rien.

**Comment by mollef** [comment]
Le 07/06/2018 à 09:42, denis-b a écrit :
>
> J'ai fait des tests :
>
>   * le se4ad n'est pas configuré pour être serveur ntp. C'est ce qui
>     fout la zone pour se4fs, et provoque l'erreur aléatoire de kerberos.
>
Ok, peux tu me donner un ex de fichier de conf type à écrire stp ? 
Actuellement je descend le paquet ntp (server) mais je laisse la 
configuration en l'état.
>
>   * il manque aussi la conf de /etc/systemd/timesyncd.conf sur se4fs
>
Même question que mettre dans le fichier de conf ? Tu le fais au niveau 
des paquet ou bien on le fait avec le script d'installation phase 2 ?

**Comment by denis-b** [comment]
pour /etc/ntp.conf, il faut juste décommenter la ligne #server et mettre
server __IP_du_ntp__ iburst

pour le reste, c'est mon problème :-)

**Comment by mollef** [comment]
Le 07/06/2018 à 10:14, denis-b a écrit :
>
> pour /etc/ntp.conf, il faut juste décommenter la ligne #server et mettre
> server *IP_du_ntp* iburst
>
Ok, mais quelle ip pour le NTP ?

Ce peut être l'amon parfois, parfois un NTP externe comme 
ntp.ac-creteil.fr ou autre.....

sur se3 nous avons ceci :

  ```cat /usr/share/se3/sbin/settime.sh
#!/bin/bash
. /etc/se3/config_c.cache.sh
[ -z "$ntpserv" ] && ntpserv="ntp.midway.ovh"
/usr/sbin/ntpdate -u -s -b $ntpserv
```

l'option -u permet de passer l'amon qui potentiellement filtre les ports 
privilégiés en sortie


  -u     Direct ntpdate to use an unprivileged port for outgoing 
packets.  This is most useful when behind a firewall that blocks 
incoming traffic to  privileged  ports,  and you want to synchronise 
with hosts beyond the firewall. Note that the -d option always uses 
unprivileged ports.


cette option est elle utilisable via le fichier de conf ntp server ?

Question subsidiaire, dois t-on prévoir de poser la question du NTP lors 
de la génération des preseed, avec par défaut le choix de celui déclaré 
dans la base se3.

> pour le reste, c'est mon problème :-)
>
ça me va ;)

**Comment by lmdsda** [comment]
Le 07/06/2018 à 10:31, Franck Molle a écrit :
> Le 07/06/2018 à 10:14, denis-b a écrit :
>  >
>  > pour /etc/ntp.conf, il faut juste décommenter la ligne #server et mettre
>  > server *IP_du_ntp* iburst
>  >
> Ok, mais quelle ip pour le NTP ?
> 
> Ce peut être l'amon parfois, parfois un NTP externe comme
> ntp.ac-creteil.fr ou autre.....
> 
> sur se3 nous avons ceci :
> 
> ```cat /usr/share/se3/sbin/settime.sh
> #!/bin/bash
> . /etc/se3/config_c.cache.sh
> [ -z "$ntpserv" ] && ntpserv="ntp.midway.ovh"
> /usr/sbin/ntpdate -u -s -b $ntpserv
> ```
> 
> l'option -u permet de passer l'amon qui potentiellement filtre les ports
> privilégiés en sortie

Si on peut passer Amon, le pool ntp me parait plus judicieux.
http://www.pool.ntp.org/zone/fr

-- 

Louis-Maurice De Sousa

**Comment by jlcf** [comment]
> Le 7 juin 2018 à 09:42, denis-b <notifications@github.com> a écrit :
> 
> J'ai fait des tests :
> 
> le se4ad n'est pas configuré pour être serveur ntp. C'est ce qui fout la zone pour se4fs, et provoque l'erreur aléatoire de kerberos.
> il manque aussi la conf de /etc/systemd/timesyncd.conf sur se4fs
> la desactivation d'ipv6 ne change rien.

Exact !
Ca marchait pas le ldapsearch GSSAPI
J’ai désactivé
Ca marche
Mais la j’ai réactivé, ca marche encore, donc en effet, ce n’était pas ca…


JL

**Comment by denis-b** [comment]
pour ntp, l'option se passe dans /etc/default/ntp. Mais peut-être qu'il vaut mieux laisser tomber la config ntp au niveau de l'install initiale de l'ad, et le faire a posteriori depuis l'interface web, car c'est typiquement le genre de truc qui peut évoluer, et c'est mieux si c'est faisable en ligne, avec un retour immédiat dans l'interface.

En revanche il faut fixer d'entrée de jeu le parametre qui permet au se4ad d'être serveur ntp  qui fait autorité pour le lan même si il n'est pas à l'heure.

**Comment by misterphi** [comment]
on rétablit l'authentification administrator en ajoutant 

- $config['dn']['admin_rdn'] = $config['admin_rdn'] . "," . $config['ldap_base_dn']; dans le fichier config.inc.php (ligne 55)
et
- $r = @ldap_bind ( $ds,"cn=".$login.",".$config['dn']["people"] , $password ) || @ldap_bind ( $ds,"cn=".$login.",".$config['dn']["admin_rdn"] , $password );
dans la fonction user_valid_password ligne 58 de functions.inc.php

mais l'authentification ne marche pas pour les autres utilisateurs qui sont dans OU=Users, car je pense qu'on peut pas binder si  l'utilisateur n'est pas dans CN=USERS. 
ça me parait logique qu'il n'y ait que les utilisateurs AD qui puissent binder
Le pb, j'ai pas trouvé comment ajouter un membre (qui est dans CN=Users) à OU=Profs par exemple

**Comment by jlcf** [comment]
Re,

Par contre :
ldapsearch  -H ldaps://se4ad -D CN=jchretien,OU=Profs,OU=Users,DC=sambaedu,DC=maison -w monmdp -b DC=sambaedu,DC=maison '(cn=jchretien)’

Fonctionne, donc on devrait pouvoir faire marcher le ldap_bind en php… Mais ca bloque pour l’instant…

JL

**Comment by denis-b** [comment]
Normalement le problème est résolu côté se4fs.

**Comment by jlcf** [comment]
Oui, je confirme !
La màj est passé et l’authentification est retombé en marche.

JL

**Comment by mollef** [comment]
je confirme.... ;)
