### ISSUE TITLE
Récréer l'entrée Admin dans l'ou=USERS et lui donner le droit d'administration des postes clients

### ISSUE THREAD

**Issue by mollef** [SambaEdu/se4#19]

**Comment by jhaesselbacher** [comment]
Pour donner les droits d'administration locale au compte admin du domaine la solution est **une gpo** 

c'est détaillé ici

https://www.it-connect.fr/gpo-definir-un-utilisateur-administrateur-local-de-tous-les-pcs/

j'ai testé la méthode avec le compte administrator du domaine et ça marche

**Il est aussi possible de passer par un vbs à lancer sur les clients**

exemple de script vps

strDomain = WScript.Arguments.Named("d")
strUser = "admin"

Set wshShell = CreateObject( "WScript.Shell" )
strComputer = wshShell.ExpandEnvironmentStrings( "%COMPUTERNAME%" )

Set objGroup = GetObject("WinNT://" & strComputer & "/Administrateurs")
Set objUser = GetObject("WinNT://strDomain/strUser")
objGroup.Add(objUser.ADsPath)

**Comment by jhaesselbacher** [comment]
En testant un client Windows 10 aujourd'hui, suite à sa jonction au domaine se4ad, je viens de remarquer que le groupe AD "Domain Admins" avait été ajouté automatiquement via gpo au groupe local "Administrateurs" du client Windows 10. "Administrator" qui doit faire partie du groupe  "Domain Admins" est donc par defaut administrateur local  sur le poste une fois qu'il est joint au domaine. C'est fonctionnel.
![image](https://user-images.githubusercontent.com/38748454/42326715-3f0ecb08-806a-11e8-9ffc-f5d4d6ed3647.png)

**Comment by mollef** [comment]
Je regarde également si c'est faisable lors de la migration ldap --> AD

**Comment by mollef** [comment]
https://github.com/SambaEdu/sambaedu-config/commit/e892ffe7d13b0fe45621be51f5dd57cc4e88d7a0
