### ISSUE TITLE
Bibliothèque de fonctions samba-tool

### ISSUE THREAD

**Issue by jlcf** [SambaEdu/se4#20]
- [X] function useradd ($prenom, $nom, $userpwd, $naissance, $sexe, $categorie, $employeeNumber) : Return $cn if succes.

 - [X]  function userdel ($cn) : Return true if userdel succes false if userdel fail

 - [X]  function groupadd ($cn, $inou, $description) : Return true if group is create false in other cases

 - [X]  function groupdel ($cn) : Return true if group is delete false in other cases

 - [X]  function groupaddmember ( $cn, $ingroup) : Return true if cn is add in ingroup false in other cases

 - [X] function groupdelmember ($cn, $ingroup) : Return true if cn is remove of ingroup false in other cases

**A faire si nécessaire** :

- [x] function grouplist ($filter) 

- [x] function groupaddlistmembers ( $cnlist, $ingroup)

**Comment by mollef** [comment]
done !
