### ISSUE TITLE
Application annuaire

### ISSUE THREAD

**Issue by jlcf** [SambaEdu/se4#21]
**Modification des scripts pour compatibilité avec l'AD**

:sparkles: **Todolist** :sparkles:
- [x] Creation de comptes
- [x] Recherche dans l'annuaire
- [x] ...

**Comment by misterphi** [comment]
Quand on crée un groupe de type "Autre" dans l'interface web, on le met dans une OU 
`ou=Groups-+ou=Groupes-+-cn=club_photo`

Dans ce cas, il faut ajouter dans sambaedu.conf
`groupes_rdn = "ou=Groupes"`

ou=Groupes est-il pertinent ?

**Comment by mollef** [comment]
hello,
Actuellement voila ce que génère /usr/share/se3/sbin/gen_se4preseed.sh depuis un se3 :
```
  cat /var/www/diconf/sambaedu.conf 
## Params du futur SE4-AD ##
se4ad_ip="10.127.164.105"
## Miroir debian ##
mirror_name="10.127.164.3"
se4ad_name="se4ad"
## Params du futur SE4-FS et domaine##
se4fs_ip="10.127.164.106"
se4fs_name="se4fs"
samba_domain="clg-hugo-gisors"
domain="clg-hugo-gisors.ac-rouen.fr"
nameserver="10.127.164.1"
## params annuaire AD##
ldap_port="636"
admin_name="Administrator"
ldap_admin_name="Administrator"
admin_rdn="cn=Users"
people_rdn="ou=Utilisateurs"
groups_rdn="ou=Groups"
rights_rdn="ou=Rights"
parcs_rdn="ou=Parcs"
computers_rdn="CN=computers"
classes_rdn="ou=classes"
equipes_rdn="ou=equipes"
matieres_rdn="ou=matieres"
projets_rdn="ou=projets"
delegations_rdn="ou=delegations"
printers_rdn="ou=Printers"
trash_rdn="ou=Trash"
lang="fr"
ldap_url="ldaps://clg-hugo-gisors.ac-rouen.fr"
cnPolicy="1"
pwdPolicy="1"
path2UserSkel="/etc/skel/user"
```
La dénomination "groupes_rdn" est donc très proche de "groups_rdn". N'y a t'il pas de risque de faire la confusion ? Au départ je l'ai faite d'ailleurs.
Un autre dénomination type "other_groups_rdn" ne serait-elle pas préférable ?

Sinon sur la question de fond de mettre ce type d'entrée dans sambaedu.conf, il me semble que oui, ce serait bien.

**Comment by misterphi** [comment]
OK

On part donc sur other_groups_rdn = "ou=Autres_groupes"

**Comment by misterphi** [comment]
je pense qu'il manque aussi le ldap_base_dn = "DC=xxx,DC=yyy" dans le sambaedu.conf

**Comment by misterphi** [comment]
Ok, je l'avais dans mon fichier de conf, mais je pensais l'avoir ajouté à la mano.

**Comment by mollef** [comment]
Voilà, sur se4-AD, le script d'installation fait ceci :
 ```
se4fs_config="/root/se4fs.conf"
echo "## ad_base_dn ##" > $se4fs_config
echo "ldap_base_dn=\"$ad_base_dn\"" >> $se4fs_config
```
Ce même fichier est ensuite récupéré  coté se4-FS par le script d'installation avant d'être ajouté à la conf :
```
ssh-keyscan -H $se4ad_ip >> ~/.ssh/known_hosts
ssh-copy-id i $dir_config/id_rsa.pub root@$se4ad_ip
scp -i $dir_config/id_rsa @$se4ad_ip:/root/se4fs.conf /root/
check_error
if [ -e /root/se4fs.conf ]; then
cat /root/se4fs.conf >> $se4fs_config
fi
```

On a besoin de la base DN pour la conf des paquet sambaedu sans que debconf ne pose de question, voila pourquoi je l'ai ajouté...

**Comment by mollef** [comment]
Normalement les différentes fonctions de base de l'annuaire sont rétablies, reste à valider l'import annuel (reste qq bugs) + nettoyage des comptes. Des issues dédiées sont déclarées ou à créer.
