### ISSUE TITLE
MàJ SE4FS 

### ISSUE THREAD

**Issue by jlcf** [SambaEdu/se4#23]
"Problèmes" rencontrés, lors d'une mise à jour des paquets SE4 sur la machine SE4FS existante (Septembre 2018):
**Préambule:**

- Verifier le bon fonctionnement de samba-tool 

- Verifier le bon fonctionnement d'une requete LDAP

- Verifier la validité du password de l'utilisateur administrator

**Etat des paquets sambaedu avant màj:**
```
ii  sambaedu-ad-client  3.9.4~XP.12
ii  sambaedu-ad-dc  3.9.4~XP.12
ii  sambaedu-boot-server   3.9.4~XP.12
ii  sambaedu-config  3.9.4~XP.12
ii  sambaedu-php-libs  3.9.4~XP.12
ii  sambaedu-web-common  3.9.4~XP.12
```

J'ai copié du depot Git local sur le SE4FS le fichier suivant:
`scp se4/sources/usr/share/doc/sambaedu/php-cli.ini.example root@SE4FS:/usr/share/doc/sambaedu/`

**Comment by jlcf** [comment]
**Etat des paquets sambaedu après màj:**
```
ii  sambaedu-ad-client  3.9.4~XP.19
ii  sambaedu-ad-dc  3.9.4~XP.19
ii  sambaedu-boot-server   3.9.4~XP.19
ii  sambaedu-config  3.9.4~XP.19
ii  sambaedu-php-libs  3.9.4~XP.19
ii  sambaedu-web-common  3.9.4~XP.19
```

Message d'Erreur pendant la màj:
```
Paramétrage de sambaedu-ad-client (3.9.4~XP.19) ...
Using short domain name -- SAMBAEDU
Joined 'SE4FS' to dns domain 'sambaedu.maison'
DNS Update for se4fs.sambaedu.maison failed: ERROR_DNS_UPDATE_FAILED
DNS update failed: NT_STATUS_UNSUCCESSFUL
```

**Comment by denis-b** [comment]
On peut l'ignorer, c'est sans gravité car on renseigne le dns par la suite.

**Comment by jlcf** [comment]
Tests suite à la màj en 3.9.4~XP.19:
Les requetes ldap et samba-tool de préambule, fonctionnent 💯  
L'authentification administrator sur l'interface web fonctionne 💯 
Le lien acces a l'annuaire retourne 👎 
`Fatal error: Cannot redeclare delete_group() (previously declared in /var/www/sambaedu/includes/ldap.inc.php:1517) in /var/www/sambaedu/includes/ldap.inc.php on line 1517`

**Comment by jlcf** [comment]
**Test import en masse directement via des fichiers CSV/XML de sconet:**

**Comment by misterphi** [comment]
sambaedu-web-common  3.9.4~XP.19

**Fatal error**: Uncaught Error: Call to undefined function have_right() in var/www/sambaedu/tests/entete_ajax.inc.php:

 il manque un
 `require_once "ldap.inc.php";`

**Comment by jlcf** [comment]
Import comptes siecle:
Les groupes ne sont pas créés !
 **solution** : 
commenter cette section dans siecle.inc.php

            /*
            else {
                // La classe existe deja dans l'annuaire.

                $temoin_classe = "";
                for ($i = 0; $i < count($tab_classe); $i ++) {
                    if ($tab_classe[$i]["nom"] == $div) {
                        $temoin_classe = "y";
                    }
                }

                if ($temoin_classe == "y") {
                    // On ajoute la classe a creer.
                    $cpt_classe ++;
                    my_echo("<p>Classe existante: $div</p>\n");
                    $tab_classe[$cpt_classe] = array();
                    $tab_classe[$cpt_classe]["nom"] = $div;
                    $tab_classe[$cpt_classe]["creer_classe"] = "n";
                    $tab_classe[$cpt_classe]["eleves"] = array();
                }
            }
