### ISSUE TITLE
Import Siecle/STS

### ISSUE THREAD

**Issue by denis-b** [SambaEdu/se4#24]
La moulinette est refaite, il faut maintenant debugger...

**Comment by mollef** [comment]
:+1: :1st_place_medal: pour Denis :)
L'import fonctionne sur un test sur les données réelles de mon étab

Par contre j'ai ceci sur les comptes elev existants :
est dans l'annuaire sans employeeNumber: bokufag
Mise à jour avec l'employeeNumber 07045: ECHEC.

Pour les profs ça passe ! --> 35 comptes existants sans employeeNumber ont été récupérés/corrigés 

nouveaux comptes semble ok et créations des groupes aussi

Création de la matière Matiere_TECHN: SUCCES
qq message de ce type :
Ajout de membres à la matière Matiere_TECHN: Pas d'enseignants pour070800?Pas d'enseignants pour070800?Pas d'enseignants pour070800?da_silvv mollef

**Comment by mollef** [comment]
Lien vers les fichiers tests :
https://github.com/SambaEdu/se3-docs/blob/master/xml_siecle_sts_test.zip

**Comment by jlcf** [comment]
👍 🥇 pour Denis :)

j'ai refais un test d'import.
a) J'efface les groupes et users avec la console AD
b) Je lance un import a partir des fichiers tests : 
https://github.com/SambaEdu/se3-docs/blob/master/xml_siecle_sts_test.zip
c) Les utilisateurs sont créés , les groupes Classes... aussi mais ils sont vides !
d) Je relance un import les groupes Classes... sont peuplés.

**Comment by denis-b** [comment]
Le 12/10/2018 à 10:05, Jean-Luc CHRETIEN a écrit :
>
> 👍 🥇 pour Denis :)
>
> j'ai refais un test d'import.
> a) J'efface les groupes et users avec la console AD
> b) Je lance un import a partir des fichiers tests :
> https://github.com/SambaEdu/se3-docs/blob/master/xml_siecle_sts_test.zip
> c) Les utilisateurs sont créés , les groupes Classes... aussi mais ils 
> sont vides !
> d) Je relance un import les groupes Classes... sont peuplés.
>
> —
>

oui, il y a un truc pas très logique dans la façon dont les groupes sons 
peulpés.

**Comment by mollef** [comment]
Les attributs employeeNumber pour les élèves ne sont pas corrigés
On obtient systématiquement :
Pas encore de cn pour employeeNumber=07569
xxx lucas est dans l'annuaire sans employeeNumber: lucas.xxx
Mise à jour avec l'employeeNumber 07569: ECHECCorrection de l'attribut 'initials': SUCCES

Les autres attributs semble corrects mais Display Name a également un pb de majuscules pour tous les nouveaux comptes
- Les nouveaux profs ont comme display name un format PRENOM.NOM à la place de Prénom.Nom
- Les nouveaux élèves ont comme display name un format Prénom.NOM à la place de Prénom.Nom
