### ISSUE TITLE
sambaedu 3.9.4~XP.35

### ISSUE THREAD

**Issue by mollef** [SambaEdu/se4#26]
Certains dossiers sont manquants par défaut dans le paquet :
* /var/www/sambaedu/tmp qui empêche la création des comptes en masse

* /var/sambaedu/Classes qui empêche la page de gestion des classes de s'afficher

**Comment by denis-b** [comment]
En fait la question est de savoir si on le fait avec un paquet sambaedu-partages, ou a posteriori dans l'interface.

**Comment by mollef** [comment]
* pour /var/sambaedu/Classes 
l'interface pourrait le créer si non existant ou bien afficher un message l'indiquant ?

* Autre chose, la page diagnostique pose des problèmes au bon fonctionnement de l'interface et n'est plus désactivable après activation dans conf_params. 

La page index.php test l'existence du paramètre alors que la page conf_params en modifie sa valeur dans sambaedu.conf --> affiche_etat = "0" ou "1"

--> solution temporaire : supprimer l'entrée manuellement   dans le fichier pour éviter l'affichage de la page diag par défaut. 
Quel est le fonctionnement à adopter ? on modifie le test dans index.php ou bien la page conf_params ?

**Comment by mollef** [comment]
/var/sambaedu/Classes sera créé le cas échéant par permsambaedu
