### ISSUE TITLE
Bloquage interface web

### ISSUE THREAD

**Issue by misterphi** [SambaEdu/se4#28]
Si on joue un peu trop vite avec l'interface web (par exemple : double ou triple clic sur le lien Diagnostic) on provoque un bloquage de l'interface.
Pour s'en sortir :
`pkill -f php-fpm`
`systemctl restart php7.0-fpm`

parfois il faut refaire un 2ième restart

Le problème vient du code suivant dans la fonction get_config() de config.inc.php
`    while (apc_fetch('config_lock')) {
        sleep(1);
    }`

A quoi ça sert ?

En supprimant ce bout de code, on n'a plus de bloquage. Est-ce indispensable ??

D'autre part pour réduire les procesus fpm, j'ai modifié  /etc/php/7.0/fpm/pool.d/sambaedu.conf avec 

`listen.group = www-admin`
`pm = ondemand`
`pm.max_children = 50`
`pm.process_idle_timeout = 5s`
`; indispensable pour ldap_sasl_bind`
`pm.max_requests = 1`

**Comment by mollef** [comment]
dixit Denis cela vient de php5 et n'est plus forcément d'actualité....
