### ISSUE TITLE
sambaedu-ad-dc.postinst buggue si pass administrator non déclaré

### ISSUE THREAD

**Issue by mollef** [SambaEdu/se4#29]
Lorsque sambaedu-ad-dc s'installe, un test  de connexion sur l'AD est effectué 

Si jamais le fichier de conf ne contient pas le mot de pass mais que la baseDN + adminDN sont bien renseignés, le script boucle sans fin sur les message suivants.

> Le serveur AD n'est pas joignable
> 
> Le serveur AD ne peut pas être joint avec les identifiants fournis.
> 
> Soit il n'est pas encore en service, dans ce cas vous devez commencer par le
> configurer en lancant....
> 
> Soit les identifiants sont incorrects.
> 
> Le serveur AD n'est pas joignable
> 
> Le serveur AD ne peut pas être joint avec les identifiants fournis.
> 
> Soit il n'est pas encore en service, dans ce cas vous devez commencer par le
> configurer en lancant....
> 
> Soit les identifiants sont incorrects.
> 
> Le serveur AD n'est pas joignable
> 
> Le serveur AD ne peut pas être joint avec les identifiants fournis.
> 
> Soit il n'est pas encore en service, dans ce cas vous devez commencer par le
> configurer en lancant....
> 
etc......

Il faut alors tuer le process à la main dans une autre console :
```
root     17496  9.9  3.3  61188 17120 pts/1    R+   17:17   0:25 /usr/bin/perl -w /usr/share/debconf/frontend /var/lib/dpkg/info/sambaedu-ad-dc.postinst configure
root     17506  8.3  0.6  11356  3132 pts/1    S+   17:17   0:21 /bin/bash -e /var/lib/dpkg/info/sambaedu-ad-dc.config configure
```
kill 17496

puis faire un dpkg-reconfigure debconf afin de baisser le niveau de priorité de debconf.

Ensuite avec apt-get -f install, la boite de dialogue debconf s'ouvre lors de la conf de sambaedu-ad-dc.  On parvient à finir la conf correctement.

Conclusion, le mot de passe administrator ne doit pas pas être sur une priorité assez élevé dans debconf.

**Comment by denis-b** [comment]
En fait c'est un pb de paquet : samedi j'ai recompilé des paquets pour corriger des trucs pour l'install linux et j'ai cassé debconf.  Je vais  corriger cela

**Comment by mollef** [comment]
réglé avec la version ~75.....
