### ISSUE TITLE
synchro de se4FS --> se4AD au moment de la mise à jour des paquets

### ISSUE THREAD

**Issue by mollef** [SambaEdu/se4#30]
La mise à l'heure synchro des serveur est indispensable à l'installation du paquet  sambaedu-ad-client

La commande suivante du postinst sort en erreur si le se4fs n'est pas synchro avec le se4AD
```
net ads join -U Administrator%Sambaedu4
gss_init_sec_context failed with [ Miscellaneous failure (see text): Clock skew too great]
kinit succeeded but ads_sasl_spnego_gensec_bind(KRB5) failed: for ldap/se4ad.clg-hugo-gisors.ac-rouen.fr user[Administrator] realm[CLG-HUGO-GISORS.AC-ROUEN.FR]: An internal error occurred.
Failed to join domain: failed to connect to AD: An internal error occurred.
dpkg: erreur de traitement du paquet sambaedu-ad-client (--configure) :
 le sous-processus script post-installation installé a retourné une erreur de sortie d'état 255
dpkg: des problèmes de dépendances empêchent la configuration de sambaedu-winbind :
 sambaedu-winbind dépend de sambaedu-ad-client ; cependant :
 Le paquet sambaedu-ad-client n'est pas encore configuré.
```

Y-a-til moyen de forcer la mise à l'heure le serveur au moment de l'installation de ce paquet ?

Si l'on reboote le serveur SE4FS, il se met à l'heure et l'installation se déroule sans pb.

**Comment by denis-b** [comment]
Le 18/10/2018 à 00:56, Franck Molle a écrit :
>
> La mise à l'heure synchro des serveur est indispensable à 
> l'installation du paquet sambaedu-ad-client
>
> La commande suivante du postinst sort en erreur si le se4fs n'est pas 
> synchro avec le se4AD
>
> |net ads join -U Administrator%Sambaedu4 gss_init_sec_context failed 
> with [ Miscellaneous failure (see text): Clock skew too great] kinit 
> succeeded but ads_sasl_spnego_gensec_bind(KRB5) failed: for 
> ldap/se4ad.clg-hugo-gisors.ac-rouen.fr user[Administrator] 
> realm[CLG-HUGO-GISORS.AC-ROUEN.FR]: An internal error occurred. Failed 
> to join domain: failed to connect to AD: An internal error occurred. 
> dpkg: erreur de traitement du paquet sambaedu-ad-client 
> (--configure) : le sous-processus script post-installation installé a 
> retourné une erreur de sortie d'état 255 dpkg: des problèmes de 
> dépendances empêchent la configuration de sambaedu-winbind : 
> sambaedu-winbind dépend de sambaedu-ad-client ; cependant : Le paquet 
> sambaedu-ad-client n'est pas encore configuré. |
>
> Y-a-til moyen de forcer la mise à l'heure le serveur au moment de 
> l'installation de ce paquet ?
>
> Si l'on reboote le serveur SE4FS, il se met à l'heure et 
> l'installation se déroule sans pb.
>

C'est systemd qui gére la synchro. on fait cela dans le postinst ad-dc :

systemctl restart systemd-timesyncd.service, normalement cela suffit. On 
peut faire un stop / start, c'est peut être plus efficace ?

Mais es-tu sûr que tu as bien testé avec la v75, j'ai ajouté cela hier.

**Comment by mollef** [comment]
`Mais es-tu sûr que tu as bien testé avec la v75, j'ai ajouté cela hier.`
Oui, voici le détail :
```
Paramétrage de sambaedu-boot-server (3.9.4~XP.75) ...
PHP Notice:  Undefined index: equipements_rdn in /var/www/sambaedu/includes/config.inc.php on line 66
1Site sambaedu already enabled
Site 000-default already disabled
[Wed Oct 17 23:50:51.847990 2018] [core:warn] [pid 26743:tid 140636929291456] AH00114: Useless use of AllowOverride in line 52 of /etc/apache2/sites-enabled/sambaedu.conf.
Paramétrage de sambaedu-ad-dc (3.9.4~XP.75) ...
# Host 10.127.164.105 found: line 1
/etc/ssh/ssh_known_hosts updated.
Original contents retained as /etc/ssh/ssh_known_hosts.old
# 10.127.164.105:22 SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u4
Paramétrage de sambaedu-php-libs (3.9.4~XP.75) ...
Paramétrage de sambaedu-ad-client (3.9.4~XP.75) ...
gss_init_sec_context failed with [ Miscellaneous failure (see text): Clock skew too great]
kinit succeeded but ads_sasl_spnego_gensec_bind(KRB5) failed: for ldap/se4ad.clg-hugo-gisors.ac-rouen.fr user[Administrator] realm[CLG-HUGO-GISORS.AC-ROUEN.FR]: An internal error occurred.
Failed to join domain: failed to connect to AD: An internal error occurred.
dpkg: erreur de traitement du paquet sambaedu-ad-client (--configure) :
 le sous-processus script post-installation installé a retourné une erreur de sortie d'état 255
dpkg: des problèmes de dépendances empêchent la configuration de sambaedu-winbind :
 sambaedu-winbind dépend de sambaedu-ad-client ; cependant :
 Le paquet sambaedu-ad-client n'est pas encore configuré.

```
En fait en creusant j'ai trouvé le coupable : openntp sur l'AD. Il ne répond pas aux requêtes de systemD coté se4FS (il doit avoir son propre client). Du coup il faut remplacer openntp par ntp coté AD. Je vais faire le nécessaire sur l'installation.

Sinon il y a moyen de faire en sorte que systemD soit un peu plus causant ? C'est un enfer à déboguer ce truc !

**Comment by mollef** [comment]
done !
