### ISSUE TITLE
Config dhcp SE4FS erronée sur le paramètre serveur DNS

### ISSUE THREAD

**Issue by mollef** [SambaEdu/se4#32]
Dans le cadre de la migration SE3 --> SE4FS/AD les paramètres réseau sont Ok, à l’exception du serveur DNS qui pointe encore sur l'ancienne valeur. 

C'est vériffiable au niveau de /etc/sambaedu/sambaedu.conf.d/dhcp.conf sur le SE4FS --> il y a donc un bug à ce niveau, le DNS devrait être la machine AD. 

En corrigeant l'entrée dans le fichier et en relançant la conf  avec /usr/share/sambaedu/sbin/make_dhcpd_conf.sh, c'est bon.

**Comment by denis-b** [comment]
Corrigé par https://github.com/SambaEdu/se4/commit/e87ebb38f33c1abe522fbbfdd87198fd875e0e1d
