### ISSUE TITLE
Importation des GPO

### ISSUE THREAD

**Issue by denis-b** [SambaEdu/se4#34]
L'importation de GPO basiques depuis l'interface fonctionne, mais celles-ci ne semblent pas être correctement prises en compte.
- verifier qu'il n'y a pas d'erreur dans les fichiers templates du paquet (j'ai édité des fichiers, et je ne suis pas sûr que Windows apprécie le formatage des xmls fait par Eclipse...)
- peut-être soucis de droits ?
- autre raison...

**Comment by jhaesselbacher** [comment]
Bonjour,
as tu essayé de sauvegarder /restaurer à partir d'une sauvegarde tes GPO avec la console RSAT pour voir si ça marche ?
IL suffit de faire un clic droit sur l'objet de stratégie de groupe / Sauvegarder / Restaurer à partir d'une sauvegarde.
Le répertoire contenant l'export de la gpo ressemble à ça 
![image](https://user-images.githubusercontent.com/38748454/48341767-3c76a680-e66e-11e8-849e-b7cc15a0770b.png)

ça peut aider au débogage

**Comment by jhaesselbacher** [comment]
je viens de tester l'import de tes GPO par les outils RSAT et elles passent
On a bien accès aux paramètres de la GPO ( onglet paramètres de la GPO importée)
Par exemple pour la gpo se4_activation smb3 on voit bien les clef de registres qui s'appliquent dans "configuration ordinateur/Préférences/Paramètres Windows/Registre"

**Comment by jhaesselbacher** [comment]
je ne sais pas encore si c'est lié a ton problème d'application des gpo, mais quand on utilise l'inferface web pour importer les gpo il créé une gpo étrange qui s'appel gpo.zip
Elle est visible avec les outils rsat 
![image](https://user-images.githubusercontent.com/38748454/49993302-a0023580-ff86-11e8-8001-86968d098ef6.png)
quoi qu'il en soit en l'état pour avoir des gpo opérationnelles je supprime celles qui on été importées par l'interface web, je désippe gpo.zip présent dans /var/www/diconf/gpo et je réimporte chaque gpo avec les outils RSAT.
pour le moment il y a juste un pb avec la gpo qui gère la remonté des profiles itinérants sur le SE4FS dans /home/profiles
je vais creuser

**Comment by mollef** [comment]
En lien avec ceci : https://github.com/SambaEdu/se4/issues/35#issuecomment-447347087

**Comment by mollef** [comment]
Le dernier paquet règle le pb 
https://github.com/sambaedu/se4/commit/85bd2c41dfaeaf4e27c5c426128f72bf0d3f237e

A tester :)
