### ISSUE TITLE
Echec installation du se4fs

### ISSUE THREAD

**Issue by jhaesselbacher** [SambaEdu/se4#36]
Lors d'une tentative récente d'installation du se4fs, lors de la phase 2 de l'install le se4fs dit qu'il ne parvient pas à contacter le se4 ad et tourne en boucle 

![image](https://user-images.githubusercontent.com/38748454/48358437-0b609b00-e69b-11e8-8074-c94db7684fc9.png)

l'install fonctionnait bien il y a encore une semaine et les conditions de test sont les mêmes.

remarque j'utilise la netinstall stable version 9.6

**Comment by jhaesselbacher** [comment]
le redémarrage du se4ad ne change rien, les adresses sont bonnes, j'ai refait 4 fois la procédure complète en repartant de 0 à partir de sambaedu-config sur le se3

**Comment by mollef** [comment]
Bonjour Julien,
Les fois où j'ai eu cela, il y  avait un problème sur le sambaedu.conf coté se4FS.
A vérifier son contenu donc et que le mot de passe défini pour administrator permet bien de binder l'annuaire AD.

**Comment by jhaesselbacher** [comment]
ok merci je vais vérifier ça

**Comment by mollef** [comment]
Si ton se4AD est DNS du SE4FS, cela ne devrait rien changer non ? Quelle était est ta conf exactement?

L'essentiel c'est que le pb soit réglé mais pour autant, le script ne devrait pas boucler dans pareil cas AMHA.

**Comment by jhaesselbacher** [comment]
Et le dns de l'ad se4ad n'y est pas référence automatiquement. Je re teste
demain

**Comment by jhaesselbacher** [comment]
Je poursuit les tests demain mais dans /etc/network/interfaces du se4fs le
dns declare était pas le se4ad mais mon amon de test qui fait la passerelle
entre mes vm et internet

Le lun. 12 nov. 2018 à 17:34, Franck Molle <notifications@github.com> a
écrit :

**Comment by mollef** [comment]
et /etc/resolv.conf est ok ?

**Comment by jhaesselbacher** [comment]
je crois que j'ai un prob avec le sambaedu-config
pour le se4fs je lui met 172.16.1.241 comme ip et il me met l'ip  que j'ai déclarée pour se4ad dans se4fs.config cad 172.16.1.240
![image](https://user-images.githubusercontent.com/38748454/48487194-c87b0080-e81d-11e8-8541-5d4c7f68e788.png)

**Comment by jhaesselbacher** [comment]
en plus il me met l'ip de mon amon virtualisé comme adresse de dns 172.16.1.254
ça ne devrait pas être l'ip du se4ad normalement ?

**Comment by denis-b** [comment]
Tant que le se4ad n'est pas en service, le serveur dns reste la passerelle. Cela est changé par la suite lors de l'installation des paquets sur le se4fs, on teste le bon fonctionnement de l'ad avant de basculer le dns.

En revanche pour l'ip de se4fs, c'est pas normal. Il s'agit bien du script de préparation de la migration se3, qui s'exécute apres l'installation de sambaedu-config sur le se3 pour préparer les presseed ?

Si oui, c'est Franck qui est fautif :-)

**Comment by jhaesselbacher** [comment]
par contre le sambaedu.conf lui semble bien renseigné 
![image](https://user-images.githubusercontent.com/38748454/48487788-8488fb00-e81f-11e8-9c14-5e034da4059a.png)
à par l'adresse du serveur DNS qui devrait normalement être celle du se4AD alors que c'est ici celle du amon virtuel 172.16.1.254

**Comment by jhaesselbacher** [comment]
après vérification l'ip donnée au se4fs après la phase 1 de l'install est pourtant bien la bonne
je pense que mon problème vient du nameserver ="172.16.1.254" qui devrait être l'ip de se4ad dans sambaedu.conf ?

**Comment by denis-b** [comment]
tant que le paquet sambaedu-ad-dc sur le se4fs ne s'est pas installé correctement (c'est à dire qu'il a pu contacter l'ad via son ip et faire une connexion ssh), le dns est bien l'amon.

**Comment by mollef** [comment]
> je crois que j'ai un prob avec le sambaedu-config
> pour le se4fs je lui met 172.16.1.241 comme ip et il me met l'ip que j'ai déclarée pour se4ad dans se4fs.config cad 172.16.1.240
> ![image](https://user-images.githubusercontent.com/38748454/48487194-c87b0080-e81d-11e8-8541-5d4c7f68e788.png)
Sur cette capture, il y a une erreur sur le nom du se4fs :
se4fs_name= se4AD --> pas glop !

Sur la seconde capture, c'est bon. Par contre, on ne voit pas si le pass administrator est déclaré. 
S'il ne l'est pas voir #29

**Comment by denis-b** [comment]
En fait pour debugger et tester l'installation de se4fs, il vaut mieux qu'il manque des parametres plutôt que d'en avoir des mal définis.
Les paquets ont été concus pour faire une installation depuis 0 avec debconf. Ils poseront donc les questions dont ils ont besoin.  Le seul prérequis est d'avoir le reseau avec l'accès internet fonctionnel en ip fixe.


Autrement dit pour debugger le truc mieux vaut ne pas passer de sambaedu.conf trop complet, car on est alors en aveugle et on ne peut pas savoir ce qu'il se passe en cas de pb. 

Ou alors lancer apt-install avec 
env DEBIAN_PRIORITY=low
voire même reinitialiser toutes les questions debconf : 
echo PURGE | debconf-communicate sambaedu-*

Comme cela on est sûr de voir toutes les questions, y compris celles qui ont déja une réponse dans le ficiher de conf.

**Comment by denis-b** [comment]
Merci de tester à nouveau avec les nouveaux paquets

**Comment by jhaesselbacher** [comment]
je viens de re-tester une install aujourd'hui jeudi 06/12/18 et l'install fraiche du se4fs ne fonctionne plus
![image](https://user-images.githubusercontent.com/38748454/49582308-e9360200-f954-11e8-95ea-310ea73d2ee0.png)

**Comment by jhaesselbacher** [comment]
je vais creuser un peu plus, ça marchait fin novembre

**Comment by denis-b** [comment]
Quelle est l'erreur d'origine ? Plus haut dans le terminal ?

Le jeu. 6 déc. 2018 à 12:52, jhaesselbacher <notifications@github.com> a
écrit :

**Comment by jhaesselbacher** [comment]
![image](https://user-images.githubusercontent.com/38748454/49583579-ec32f180-f958-11e8-9c87-e4d50d0e1bd1.png)
![image](https://user-images.githubusercontent.com/38748454/49583599-fc4ad100-f958-11e8-9434-113a5d498d3c.png)
![image](https://user-images.githubusercontent.com/38748454/49583643-1be1f980-f959-11e8-9dc3-e606d15ffe22.png)
![image](https://user-images.githubusercontent.com/38748454/49583659-2a301580-f959-11e8-9364-3cdb567d47bb.png)
![image](https://user-images.githubusercontent.com/38748454/49583682-3ddb7c00-f959-11e8-8c0d-bfb08032a140.png)
![image](https://user-images.githubusercontent.com/38748454/49583705-4d5ac500-f959-11e8-98f4-54fbdea947c3.png)
![image](https://user-images.githubusercontent.com/38748454/49583723-5a77b400-f959-11e8-9051-afff0723e644.png)
![image](https://user-images.githubusercontent.com/38748454/49583750-6ebbb100-f959-11e8-9d53-251ff801ddd9.png)

ci dessus le déroulement de l'install

**Comment by jhaesselbacher** [comment]
les premiers problèmes sont ici 
![image](https://user-images.githubusercontent.com/38748454/49584564-0ae6b780-f95c-11e8-8882-0121e169c1cf.png)

**Comment by jhaesselbacher** [comment]
![image](https://user-images.githubusercontent.com/38748454/49584586-19cd6a00-f95c-11e8-822b-876f6a8896f6.png)

**Comment by denis-b** [comment]
Le 06/12/2018 à 13:37, jhaesselbacher a écrit :

Que contient /etc/dhcp/dhcpd.conf ?

**Comment by jhaesselbacher** [comment]
![image](https://user-images.githubusercontent.com/38748454/49586568-ceb65580-f961-11e8-9361-b56940e6e2cf.png)
![image](https://user-images.githubusercontent.com/38748454/49586592-de359e80-f961-11e8-9ef7-94b31491ea2f.png)
![image](https://user-images.githubusercontent.com/38748454/49586608-e8579d00-f961-11e8-9a7c-f4e48ca73010.png)

**Comment by jhaesselbacher** [comment]
il contient 
![image](https://user-images.githubusercontent.com/38748454/49588070-13dc8680-f966-11e8-8c3f-5ff14b821f51.png)

**Comment by denis-b** [comment]
Il manque des choses. Tu as migré depuis un se3 ?

**Comment by jhaesselbacher** [comment]
oui depuis un se3 procédure de génération du se4ad.pressed et se4fs.preseed
installation depuis la net install debian stretch 9.6 en auto install via les pressed
j'install d'abord le se4ad pas de pb,
puis le se4fs

**Comment by denis-b** [comment]
Mets à jour les paquets cela doit être bon.

Le 06/12/2018 à 15:03, jhaesselbacher a écrit :

**Comment by jhaesselbacher** [comment]
ça va beaucoup mieux
j'ai juste deux erreurs qui persistent 
![image](https://user-images.githubusercontent.com/38748454/49590420-29ed4580-f96c-11e8-8d03-694605c7412e.png)

![image](https://user-images.githubusercontent.com/38748454/49590430-307bbd00-f96c-11e8-9642-113ff9fbe9de.png)

mais l'interface de gestion web est maintenant accessible
![image](https://user-images.githubusercontent.com/38748454/49590491-51dca900-f96c-11e8-80ad-eaea77f36bfd.png)

**Comment by jhaesselbacher** [comment]
et le serveur DHCP fonctionne bien

**Comment by jhaesselbacher** [comment]
j'importe bien les GPO dans l'interface web
![image](https://user-images.githubusercontent.com/38748454/49590627-a718ba80-f96c-11e8-85d9-55403ab88f59.png)

**Comment by denis-b** [comment]
Ca c'est pas sûr que cela fonctionne bien !

Il faut regarder depuis la console AD si les gpo sont bien prises en compte.

Sinon il faut les importer depuis la console : tu dezippe le fichier et 
tu les importes deuis la console AD.

Le 06/12/2018 à 15:36, jhaesselbacher a écrit :

**Comment by jhaesselbacher** [comment]
ok je peux essayer mais c'est rangé ou dans l'arborescence du se4fs ?

**Comment by jhaesselbacher** [comment]
ok c'est dans /var/www/sambaedu/gpo/templates/

**Comment by jhaesselbacher** [comment]
je poursuis les tests demain matin, et merci pour le coup de main

**Comment by jhaesselbacher** [comment]
suite à nos derniers échanges concernant les modifications à faire sur le SMB.conf pour la bonne application du script sh destiné à créer les répertoires personnels des utilisateurs à la première connexion,

j'ai retenté aujourd'hui l'installation d'un SE4FS et l'installation est de nouveau en échec 
Les problèmes commences ici lors de l'install 
![image](https://user-images.githubusercontent.com/38748454/49799540-82925900-fd45-11e8-8325-106e20203b50.png)

puis ça continu ici 
![image](https://user-images.githubusercontent.com/38748454/49799585-9b027380-fd45-11e8-9ab7-3e56b26de37b.png)
![image](https://user-images.githubusercontent.com/38748454/49799627-b3728e00-fd45-11e8-99f5-e51b60b04044.png)
![image](https://user-images.githubusercontent.com/38748454/49799652-c1c0aa00-fd45-11e8-89ca-290edd07f14c.png)
![image](https://user-images.githubusercontent.com/38748454/49799674-d13ff300-fd45-11e8-9bea-2aa5b9c16160.png)
![image](https://user-images.githubusercontent.com/38748454/49799702-e1f06900-fd45-11e8-957a-ef31b731baa0.png)
![image](https://user-images.githubusercontent.com/38748454/49799739-f0d71b80-fd45-11e8-9970-6c68f2ecf05e.png)
![image](https://user-images.githubusercontent.com/38748454/49799755-ff253780-fd45-11e8-8494-31564370affb.png)
![image](https://user-images.githubusercontent.com/38748454/49799776-12d09e00-fd46-11e8-9ce9-defbe044026b.png)
![image](https://user-images.githubusercontent.com/38748454/49799796-1d8b3300-fd46-11e8-994d-e15263d7bd4d.png)

**Comment by jhaesselbacher** [comment]
chgrp -R "Domain Users" /home/profiles passe bien
apt-get -f donne
![image](https://user-images.githubusercontent.com/38748454/49804148-23871100-fd52-11e8-8f65-3647cce28d6e.png)

**Comment by mollef** [comment]
Donc Voila, tes paquets sont passés. Le chgrp -R "Domain Users" /home/profiles avait simplement lieu trop tôt dans l'ordre d'installation des paquets ou bien il faut ajouter une tempo pour que l'annuaire soit bien en ligne au moment où on lance la commande... A creuser !

**Comment by mollef** [comment]
Autre chose, ajoutes ceci dans ton sambaedu.conf.
cours_rdn = "ou=cours"

J'ai poussé une maj sur sambaedu-config afin qu'il soit ajouté (v 0.25) mais inutile de refaire toute l'installation pour cela.

**Comment by jhaesselbacher** [comment]
ok merci ça fonctionne

**Comment by mollef** [comment]
https://github.com/SambaEdu/se4/commit/fe0d8956be9c89be2bddad65d43632aea1dc840f
