### ISSUE TITLE
Attributs utilisateurs non récupés par sambatool --classic-upgrade

### ISSUE THREAD

**Issue by mollef** [SambaEdu/se4#37]
il manque des attributs dans l'AD coté fiche des utilisateurs une fois le classic upgrade effectué. En fait sambatool ne semble pas migrer tous les attributs de ldap vers AD. Un effet de bord visible c'est que l'on ne parvient pas à trier les membres d'un groupe puisque l'attribut "sn" n'existe pas.

Sont manquants :
```
                "sn", // Nom
                "givenname", // Pseudo -> Prenom
                "mail", // Mail
                "telephonenumber", // Num telephone
                "physicaldeliveryofficename", // Date de naissance,Sexe (F/M)
                "title", // numero unique siecle
                "initials", // pseudo 
```

Initials ne pourra être récupéré en l'état car semble limité en taille.

Pour le autres, j'adapte le script d'installation sur l'AD comme suggéré dans la doc 
https://wiki.samba.org/index.php/Migrating_a_Samba_NT4_Domain_to_Samba_AD_(Classic_Upgrade)#Not_all_attributes_were_copied_when_migrating_from_passwd_backend_.3D_ldapsam

**Comment by denis-b** [comment]
T'est sûr que c'est utile ? il me semble maintenant que l'import siecle remet les choses en place.

Pour initials, je crois me rappeler qu'il est impérativement de la forme D.B. Je l'ai défini dans l'import annuel, mais me souviens d'avoir eu des problèmes avec les comptes avec cela, du coup sur mon annuaire je ne l'ai pas mis à jour. Il faudrait tester.

**Comment by mollef** [comment]
Autant que l’annuaire soit le plus correct en sortie d'upgrade avant même de refaire l'import derrière histoire d'éviter les blagues. J'ai qq chose qui fonctionne. Pour initial, il faut 6 lettres maxi, donc j'ai tronqué le prénom à 5+1 lettre du nom. Si tu veux que je m'alignes sur P.N, dis moi, à mois que ce soit modifié d'autorité lors de l'import SIECLE/STS

**Comment by denis-b** [comment]
Pour initials il me semble que le ldapmodify  refusait autre chose que x.yyy.; Il y a une contrainte de schéma.
Attention, je me demande si windows n'utilise pas cet attribut comme login si il est présent...

**Comment by denis-b** [comment]
Regarde ce que j'ai fait dans siecle. Inc. Php. autant être cohérent

Le mar. 13 nov. 2018 à 10:26, Franck Molle <notifications@github.com> a
écrit :

**Comment by mollef** [comment]
C'est bien P.N
Je ferai donc pareil....

⁣Envoyé par BlueMail ​

Le 13 nov. 2018 11:05, à 11:05, denis-b <notifications@github.com> a écrit:

**Comment by mollef** [comment]
https://github.com/SambaEdu/sambaedu-config/commit/3ec619a67c2f789aaaec166989214f8230dd38e2
https://github.com/SambaEdu/sambaedu-config/commit/4113c08fa9d3a50147f1ae0bd74241515c6344cd
