### ISSUE TITLE
Import Annuel

### ISSUE THREAD

**Issue by mollef** [SambaEdu/se4#38]
Lorsque l'on opère un import annuel, les groupes principaux Profs et élèves ne sont pas vidés.

Ces comptes sont donc toujours membre de leur groupe principal et conservés dans l'ou=Profs ou ou=eleves alors qu'ils devraient être membre d'aucun groupe voire envoyés dans l'ou=Trash

Exemple d'un compte concerné suite à l'import de mon annuaire d'étab :
ALAIN MIMOUN 
Membre des groupes :
Profs Domain Unix group
         retirer du groupe 

Ce compte ne devrait plus appartenir au groupe profs car non présent dans STS. Il n'est d'ailleurs dans aucune équipe.

**Comment by misterphi** [comment]
Problème résolu :
- tous les groupes (sélectionnés) sont vidés et re-peuplés lors d'un import annuel
- tous les groupes sont mis à jour ( ajout des membres manquants, et retrait des membres en trop) par rapport aux données des xml, **hors** import annuel

**Comment by mollef** [comment]
Bravo  misterphi :+1:
