### ISSUE TITLE
Appli Annu (suite et fin)

### ISSUE THREAD

**Issue by jlcf** [SambaEdu/se4#39]
Que faire de :
- Désactiver le compte 
- Créer le dossier perso
- Régénérer le profil

Qui sont trois fonctionnalités qui ne fonctionnent plus en ce moment.

**Comment by denis-b** [comment]
- Desactiver le compte : c'est dans la lib  :
modify_ad($config, $cn, array('useraccountcontrol'=>514));
- Créer le dossier perso : c'est automatique, non ?
- Régénerer le profil : beaucoup moins utile qu'avant...
