### ISSUE TITLE
Intégration des Win7 et Win10

### ISSUE THREAD

**Issue by azertyqsdf956** [SambaEdu/se4#40]
Bonsoir,

J'ai essayé d'intégré une Win7 et une W10 sur le domaine SE4. Le script se lance bien en revanche après un redémarrage il s’arrête et me propose de me connecter sur le adminse3. Et rien ne change hormis que le groupe de travail se nomme "tmpse3". 

Savez-vous si le script d'intégration est OK ? 

Avez-vous déjà intégrer des machines W10 ou W7 ?

Faut-il faire quelques choses au préalable sur la machine avant de l'intégré.

En  vous remerciant.

**Comment by azertyqsdf956** [comment]
On est bien d'accord que c'est ce script là qu'il faut lancer.

**Comment by denis-b** [comment]
Les scripts sont encore présents pour des expérimentations de clonage, mais ne doivent pas être utilisés, ils font plus de dégâts qu'autre chose...

**Comment by azertyqsdf956** [comment]
Bonjour,

denis-b merci pour votre retour.

Je retenterai avec les propriétés système (comme avec un windows server).

**Comment by mollef** [comment]
Pour info, une fois la machine au domaine AD, il est aussi possible d'installer la console RSAT comme pour un windows server. J'ai commencé un bout de doc, il est disponible ici :

http://wawadeb.crdp.ac-caen.fr/test/adminl_rsat_gen_web/co/install_rsat.html

**Comment by azertyqsdf956** [comment]
Merci pour l'information :)

**Comment by azertyqsdf956** [comment]
Bonsoir,

Sur W7 pas de soucis

![image](https://user-images.githubusercontent.com/45298773/50111328-d668da80-023c-11e9-848f-bd8d81ae3b67.png)


![image](https://user-images.githubusercontent.com/45298773/50111377-f0a2b880-023c-11e9-8506-ce2fd4eed89c.png)


![image](https://user-images.githubusercontent.com/45298773/50111408-087a3c80-023d-11e9-8de2-68b4767c452d.png)

![image](https://user-images.githubusercontent.com/45298773/50111488-2d6eaf80-023d-11e9-8b30-a28413d02b68.png)


![image](https://user-images.githubusercontent.com/45298773/50111509-395a7180-023d-11e9-8c4b-37bd5afd8623.png)

**Comment by azertyqsdf956** [comment]
Sur W10_1803 en revanche message d'erreur

![image](https://user-images.githubusercontent.com/45298773/50112715-4462d100-0240-11e9-840d-d7a1188aa75b.png)

**Comment by azertyqsdf956** [comment]
Sur W10_1709 ça ne marche pas mais le message d'erreur est différent et il me propose de mettre un compte admin du domaine avant le message d'erreur.

![image](https://user-images.githubusercontent.com/45298773/50112807-7bd17d80-0240-11e9-8886-3f18fb19a536.png)


![image](https://user-images.githubusercontent.com/45298773/50112868-a7546800-0240-11e9-9b19-54e7344d74ca.png)

**Comment by denis-b** [comment]
Le 17/12/2018 à 21:11, azertyqsdf956 a écrit :
>
> Sur W10_1803 en revanche message d'erreur
>
Il faut vérifier que la résolution dns se fait bien :

ping demo.homenet.org

ping se4ad.demo.homenet.org

Doivent renvoyer l'ip du se4ad.


L'erreur sur le w7 laisse penser qu'il y a un souci avec la résolution 
dns malgré tout.

Verifier qu'il n'y a pas un autre serveur dns sur le réseau configuré 
pour résoudre demo.homenet.org

**Comment by azertyqsdf956** [comment]
Faut-il faire quelques choses au préalable sur les W10 avant de les intégrer au domaine ? 

En vous remerciant.

**Comment by jhaesselbacher** [comment]
Jai eu aussi cette blague. A la fin de la phase 1 de l'install de ton se4fs, avant que le se4fs ne redemarre et quil te demande de te connecter en root/se4fs il faut que ta vm se3 soit down.
Redemarre aussi ton se4ad et ton se4fs avant de tenter la jonction de ton client w10 et essai de mettre ton nom long de domaine demo.bidule.machin au moment de joindre la machine au domaine.
Jai encore teste le tout aujourdhui avec un w10 en 1803 et ca marche nickel

**Comment by azertyqsdf956** [comment]
Bonsoir,

Merci Denis-b pour l'aide. Effectivement je n'ai pas penser à cela. 

Du coup j'ai créer un DNS sur ma box internet et j'ai désactiver le DHCP de la box.

L'intégration de la W10 1803 c'est faites sans problèmes. Faut juste entrer le nom de domaine samba plus son suffixe DNS.
