### ISSUE TITLE
Debian 10 "Buster" support

### ISSUE THREAD

**Issue by Neustradamus** [SambaEdu/se4#41]
https://wiki.debian.org/DebianBuster

**Comment by azertyqsdf956** [comment]
Bonjour,

Est ce qu'un déploiement des clients linux est prévu comme dans le SE3 ?Je profite de cette issue pour poser la question.

**Comment by mollef** [comment]
Oui, c'est prévu et commencé : https://github.com/orgs/SambaEdu/projects/8

**Comment by mollef** [comment]
Oui d'ailleurs la réponse de Denis allait dans ce sens, le serveur. Après quel intérêt mis à part pour monter en version côté samba ce qu'il est possible de faire avec un backport...?
Il reste encore à faire avec stretch et elle va rester la version stable encore un moment...

**Comment by denis-b** [comment]
Vérifier de temps à autre que l'upgrade passe est un bon test de qualité.
Mais vu que les paquets sont conformes debian, rien ne devrait poser
problème.

Le sam. 22 déc. 2018 à 11:12, Franck Molle <notifications@github.com> a
écrit :

**Comment by Neustradamus** [comment]
+ PHP 7.3 vu que PHP 7.0 est EOL.
