### ISSUE TITLE
Suppression d'un prof

### ISSUE THREAD

**Issue by misterphi** [SambaEdu/se4#43]

**Comment by misterphi** [comment]
Quand on supprime un user du groupe Profs via l'interface web, il faudrait le supprimer de tous ses groupes.

**Comment by mollef** [comment]
p de filtre un peu large sans doute... Il y en a sûrement d'autres. Le fait de supprimer le groupe principal semble logique d’entraîner la suppression de l'affiliation aux groupes secondaires

**Comment by misterphi** [comment]
Modif effectuée pour tous les utilisateurs.
