### ISSUE TITLE
Problèmes détectés sur les clients Windows du domaine SE4AD-FS

### ISSUE THREAD

**Issue by Mwaye** [SambaEdu/se4#6]
J'ai mis en commentaire le message d'origine car il a été scindé en plusieurs issues par soucis de lisibilité.

**Celui-ci ne permet donc plus que de suivre les problèmes détectés sur les clients Windows du domaine SE4AD-FS.**

**- id domaine ok mais connexion client à l'AD impossible :**
Après l'installation avec succès du SE4AD avec le preseed modifié, si on test de se loguer au domaine NT ou AD avec les postes anciennement SE3 cela ne fonctionne pas. L'ID domaine semble bien repris du SE3 mais la connexion ne se fait pas. Il doit y avoir des modifs à faire sur les clients et de la conf serveur AD et FS à faire.
Par contre si on intègre un poste directement sur le SE4AD ça fonctionne impecc'.

**- administrator n'est pas intégré au groupe admin du poste :**
Autre point remarqué, si on intègre un poste dans le nouveau domaine et qu'on se logue en administrator, la session est ouverte sans droits "administrateur local" mais c'est peut-être un choix volontaire de votre part.

Benjam

> Bonjour
> 
> Avec mon collègue Julien nous faisons des tests de migration de SE3 vers SE4(AD-DS) avec les scripts dispo ici même.
> Nous avons constaté plusieurs pb, qui sont normaux à ce stade d'avancement, mais que nous vous faisons remonter pour info.
> Cela peut peut-être vous aider à avancer un peu vos scripts.
> 
> **_Voici quelques-uns des problèmes que nous avons rencontrés, ils sont pour cerrtains, liés entre eux et peut-être facilement réparable quand on connait vos scripts :_** 
> 
> **- Problème sda-xvda :** https://github.com/SambaEdu/se4/issues/7
> Le script qui génère la conf auto preseed des install AD et FS ne prend en compte que les disques /dev/sda. Ce qui pose problème lors d'installation Xen (par ex) car les disques sont reconnus en /dev/xvda.
> Il y a bien eu prise en compte du pb si on se réfère à la doc GitHub mais le script ne le prend pas encore en compte.
> Si on modifie à la main les preseed, l'installation Debian 9 se fait bien toute seule et on passe aux étapes suivantes.
> 
> **- organisation de l'AD :**
> ![2018-05-03 - se4ad - groupes-machines-ad](https://user-images.githubusercontent.com/1438205/39579663-9923213e-4ee7-11e8-82a3-3f8503f5618c.png)
> Les entrées machines et utilisateurs sont dans des groupes au lieu (ou en plus pour les users) d'être dans des OU ce qui pose des pb d'application des stratégies à des users ou postes.
> 
> **- id domaine ok mais connexion client à l'AD impossible :**
> Après l'installation avec succès du SE4AD avec le preseed modifié, si on test de se loguer au domaine NT ou AD avec les postes anciennement SE3 cela ne fonctionne pas. L'ID domaine semble bien repris du SE3 mais la connexion ne se fait pas. Il doit y avoir des modifs à faire sur les clients et de la conf serveur AD et FS à faire.
> Par contre si on intègre un poste directement sur le SE4AD ça fonctionne impecc'.
> 
> **- se4fs problème fichier slapd.conf non trouvé et conf non wget :** https://github.com/SambaEdu/se4/issues/8
> Lors de l'install du SE4FS, la phase2 s'arrête sur une erreur de slapd.conf non trouvé.
> Si on gratte on voit que le script phase2_se4fs ne contient pas toutes les fonctions utilent (cf phase2_se4ad) et n'importe pas la conf depuis l'ancien SE3.
> Si on recupère la conf manuellement, qu'on la place dans /etc/sambaedu/, qu'on modifie le phase2_se4fs en y ajoutant les fonctions ; le script va un peu plus loin mais fini par remettre une erreur slapd.conf. En fouillant un peu, on voit que dans /etc/ldap/ il y a un repertoire (au lieu d'un fichier) slapd.conf qui se crée et qui contient les entrées qui devraient être normalement dans le fichier de conf slapd.conf.
> (Je sais qu'il est en construction ce script mais ça peut faire avancer le schmilblick)
> 
> **- administrator n'est pas intégré au groupe admin du poste :**
> Autre point remarqué, si on intègre un poste dans le nouveau domaine et qu'on se logue en administrator, la session est ouverte sans droits "administrateur local" mais c'est peut-être un choix volontaire de votre part.
> 
> Merci d'avance de vos pistes et avancées.
> @micalement,
> 
> Benjam

**Comment by denis-b** [comment]
Pour la migration des postes déjà au domaine je pense qu'il faut annuler toutes les dégradations faites pour pouvoir se connecter en mode nt4  : 
En gros réactiver le protocole smb2, et sans doute virer certaines clés. 

Essayez :  

reg.exe del "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\NetworkProvider\HardenedPaths" /v "\\*\netlogon"  /F
reg.exe del "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Policies\Microsoft\Windows\NetworkProvider\HardenedPaths" /v "\\*\netlogon"  /F
reg.exe del "HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "DomainCompatibilityMode"  /F
reg.exe del "HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "DNSNameResolutionRequired" /F



sc.exe config lanmanworkstation depend= bowser/mrxsmb10/nsi
sc.exe config mrxsmb10 start= disabled
sc.exe config lanmanworkstation depend= bowser/mrxsmb20/mrxsmb10/nsi
sc.exe config mrxsmb20 start= auto

:: necessaire pour W10 > 1709, ne pose pas de probleme pour les versions anterieures
dism.exe /online /disable-feature /quiet /norestart /featurename:SMB1Protocol
dism.exe /online /disable-feature /quiet /norestart /featurename:SMB1Protocol-Client
dism.exe /online /disable-feature /quiet /norestart /featurename:SMB1Protocol-Server
dism.exe /online /enable-feature /quiet /norestart /featurename:SMB1Protocol-Deprecation

Il faut peut-être virer certaines gpo locales aussi, mais il me semble me souvenir que cela suffit.

**Comment by Mwaye** [comment]
Merci pour ces infos.
C'est justement ces infos de modifs spécifiques "mode NT" que l'on 
voulait avoir.
On en avait une partie mais pas toutes.

Ca devrait permettre aux clients W7/W10 de redetecter automatiquement le 
domaine ?
Car pour le moment les clients cherchent tujours le domaine SAMBAEDU3 et 
non celui que l'on a mis en mode AD.
Ou il y a d'autres manip à faire ? Comme ça on va pouvoir tester et 
avancer un peu.

De plus, nous n'avons que très peu de clients Linux mais quelles sont 
les manipulations pour ces postes (même si c'est beaucoup moins pressant 
pour nous de faire ces tests) ?

Merci
Benjam


Le 03/05/2018 à 16:52, denis-b a écrit :

**Comment by denis-b** [comment]
A mon avis c'est ici que cela se joue : 
reg.exe del "HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "DomainCompatibilityMode"  /F
reg.exe del "HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "DNSNameResolutionRequired" /F

On repasse en mode dns, et donc il faut aussi vérifier que le se4ad est bien défini comme serveur dns dans la conf dhcp.

**Comment by Mwaye** [comment]
Quelle réactivité.

Oui nous avons déjà modifié le DNS au niveau du dhcp et vérifier qu'il 
est bien pris en compte.
On ping bien le serveur depuis les postes mais pas l'inverse (car au 
niveau du serveur le dns n'est pas lui-même en plus du dns forwarder je 
pense).
Nous allons tester ça dès que possible.

**Benjam
*

*
Le 03/05/2018 à 18:07, denis-b a écrit :

**Comment by mollef** [comment]
Concernant la partie Xen, un nouveau paquet prend en compte cette particularité : 
https://github.com/SambaEdu/sambaedu-config/releases/tag/0.21

C'est en ligne branche testing

**Comment by mollef** [comment]
Pour la partie installation du script se4fs[ l'issue dédiée est là ](https://github.com/SambaEdu/se4/issues/8):  https://github.com/SambaEdu/se4/issues/8

**Comment by jhaesselbacher** [comment]
Concernant le changement de domaine, la sortie du domaine sambaedu3 et le passage sur le nouveau domaine voila ou j'en suis 

Pour désactiver le protocole smb1 et que le service netlogon du poste client windows fonctionne encore après cette opération il faut suivre précisément ces étapes 👍 

En effet, jusqu'ici dans nos test la désactivation de smb1 et la réactivation de smb2/3 provoquait un dysfonctionnement du service netlogon Windows ( le service refuse de démarrer car il est encore associé au protocole smb1 ) 

- Ces commandes powershell sont à lancer en cmd en tant qu'administrateur et forcent l'utilisation de smb2/3 par le service netlogon ( en ayant préalablement désactiver l'utilisation de smb1 par netlogon ). 

powershell.exe -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "& {Set-itemproperty -path “HKLM:\System\CurrentControlSet\Services\LanmanServer\Parameters” SMB1 -Type Dword -Value 0 -Force}"

powershell.exe -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "& {Set-itemProperty -path “HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters” SMB2 -Type Dword -Value 1 -Force}"

powershell.exe -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "& {Set-itemProperty -path “HKLM:\SYSTEM\CurrentControlSet\services\lanmanworkstation” -name “DependOnService” -value “Bowser”, “MRxSmb20”, “NSI” -type MultiString}"

powershell.exe -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "& {Set-itemProperty -path “HKLM:\SYSTEM\CurrentControlSet\services\mrxsmb10” -name “Start” -type Dword -Value 4 -Force}"

powershell.exe -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "& {Set-itemProperty -path “HKLM:\SYSTEM\CurrentControlSet\services\mrxsmb20” -name “Start” -type Dword -Value 2 -Force}"

- Les clefs de registre à nettoyer 

reg.exe delete "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\NetworkProvider\HardenedPaths" /v "\\*\netlogon"  /F
reg.exe delete "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Policies\Microsoft\Windows\NetworkProvider\HardenedPaths" /v "\\*\netlogon"  /F
reg.exe delete "HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "DomainCompatibilityMode"  /F
reg.exe delete "HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "DNSNameResolutionRequired" /F

- La désinstallation de smb1

Echo necessaire pour W10 > 1709, ne pose pas de probleme pour les versions anterieures
dism.exe /online /disable-feature /quiet /norestart /featurename:SMB1Protocol
dism.exe /online /disable-feature /quiet /norestart /featurename:SMB1Protocol-Client
dism.exe /online /disable-feature /quiet /norestart /featurename:SMB1Protocol-Server
dism.exe /online /enable-feature /quiet /norestart /featurename:SMB1Protocol-Deprecation

- La Suppression des GPO

del /Q /S /F c:\windows\System32\GroupPolicy\*


Une fois ces commandes passées netlogon fonctionne bien mais nous sommes tout de même encore obligés de joindre manuellement le nouveau domaine se4ad avant de pouvoir ouvrir une session sur ce dernier ( changement de domaine à scripter via un vbs ou une commande powershell

julien

**Comment by mollef** [comment]
Pbs réglés ou traités dans les issues dédiées.
